### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by joflex71** [FreetimeStudio/Adventure-Kit-Public#10]
Hallo,

ich habe mir vom Unreal Marktplace Ihr Plugin gekauft und heruntergeladen.
Leider öffnet sich das Plugin nicht und wird auch nicht im Content Browser angezeigt.
Können sie mir sagen, was ich falsch mache?
Anbei der Crash Report.
[adventure.log](https://github.com/FreetimeStudio/Adventure-Kit-Public/files/4208909/adventure.log)

VG

Joflex

**Comment by freetimecoder** [comment]
Hallo @joflex71 !

Danke für den Report! Aus ihm geht hervor, dass eine falsche Instruktion für den Crash verantwortlich ist. Ich habe einen fix an den Marketplace geschickt, dieser sollte innerhalb der nächsten Tage als Update zur Verfügung stehen.

Das Plugin wird nicht im Content Browser angezeigt, weil es keinen Content enthält. Alle Beispiele und Templates befinden sich in UE_4.XX/Engine/Plugins/Marketplace/AdvKitPlugin/AdditionalContent. Im Plugin Ordner befindet sich auch eine Readme die erklärt wie der Inhalt zu installieren ist.

Grüße
