### ISSUE TITLE
Projectile Questions on Integrating a Module

### ISSUE THREAD

**Issue by hollywoodvrgames** [FreetimeStudio/Adventure-Kit-Public#2]
I need to know these things
1. Is there a way to get the Reference of the Spawned projectile?
2.  Owner(of the projectile) reference maybe

**Comment by freetimecoder** [comment]
1) When a weapon shoots a projectile the FireProjectile method is called. This method can be overriden in blueprint to hook in custom logic. Add a call to the parent function and its return value is the spawned projectile. 

In this fashion the bow sets the arrow speed when firing:
![bow_projectile](https://cloud.githubusercontent.com/assets/7116086/17342255/a11c4474-58f8-11e6-9887-8f99b01a0aa3.png)

2) The projectile's Owner is the weapon that fired it and the projectile's Instigator the character that fired the weapon.
