### ISSUE TITLE
Character not performing animations accordingly.

### ISSUE THREAD

**Issue by Xanadron** [FreetimeStudio/Adventure-Kit-Public#3]
Hi,, i have bought this pack and i installed the templates. I created a Parkour project and migated all content to my own project. I tried to remake most of the stuff (pretty much everyyhing) and i ended up with the character not grabbing the ledge, ladder etc. I am using the 4.11 version. A thing that i noticed is that when the character is in the zone it cannot jump. The reason i migrated everything is because i have done half of my game and it would be ridiculous to start all over again with a default template. Looking forward to your reply! Also let me know if you need any screenshots.

**Comment by freetimecoder** [comment]
First it is necessary to reparent your character to the AdvKitCharacter class. The 4.11 version of the kit still uses character actions for transitions. Each character has one or multiple actions configured in the "Default Actions" property. An action governs which Anim Montage the character plays and how it goes from zone to zone.

How a transition action is setup can be seen in this and the video after it:
https://www.youtube.com/watch?v=mHeV1uwUjpQ&index=6&list=PLA03OHAaHgYrsh5HImQhWhO5s0nDPyj2g

In order for the character to use the same mechanics as the parkour character you need to assign it the same actions as the parkour character has and in case your character uses a different skeleton retarget the anim montages used by the actions and assign them in the actions' properties.

I suppose an update to 4.12 is out of the question? In the kit's v2.0 for 4.12 and 4.13 transitions no longer rely on animations, but instead entirely on the Anim Blueprint, making it much easier to retarget everything.

Kind Regards

**Comment by Xanadron** [comment]
I understand, i downloaded the 4.12 version of the kit and installed it. Now the Adventure Kit Core doesn't show up when i try to add a feaure pack, as you do in the tutorial.

**Comment by freetimecoder** [comment]
Make sure you have downloaded this exact zip: https://github.com/FreetimeStudio/Adventure-Kit/releases/download/2.0.0-alpha.2/AdvKitRelease_412_200alpha2.zip

and that you have copied all the required files into their respective directories:
- Copy the AdvKitPlugin folder to UE_Install_Dir/4.XX/Engine/Marketplace/Plugins/
- Copy the content of the Templates folder to UE_Install_Dir/4.XX/Templates/
- Copy the content of the FeaturePacks folder to UE_Install_Dir/4.XX/FeaturePacks/ 

Kind Regards

**Comment by Xanadron** [comment]
Hi, 

I wasn't able to implement the system in my project therefore i decided to make the game in yours. What i want to know before i start building it up again is could i use the demo game mode, demo character and demo player controller blueprints for all my maps? What i really want is my game to include everything that the kit provides and have that in every map. Would you be able to tell me if this could work, if not what would be the best way to have everything in one place? Thank you, and looking forward to your reply!

Best regards,
Alex
