### ISSUE TITLE
Can't let go of anything

### ISSUE THREAD

**Issue by Xanadron** [FreetimeStudio/Adventure-Kit-Public#4]
Hi, i followed all the tutorials but for some reason the character won't let go from any ledge or ladder and it cannot make a transition down to a ledge. Could you give me an advice?

**Comment by freetimecoder** [comment]
Hi @Xanadron,
In order for the character to let go of zones you need to call the method "LetGoOfZone" on the character when the player presses a button (the crouch button for example).

Kind Regards

**Comment by Xanadron** [comment]
Thank you! 

  On Sat, 17 Sep, 2016 at 11:28, Pascal Krabbenotifications@github.com wrote:  
Hi @Xanadron,
In order for the character to let go of zones you need to call the method "LetGoOfZone" on the character when the player presses a button (the crouch button for example).

Kind Regards
