### ISSUE TITLE
Note doxygen as source requirement

### ISSUE THREAD

**Issue by sagron** [FreetimeStudio/Adventure-Kit-Public#5]
doxygen needs to be listed under github source 4.14 and later requirement on the wiki. The deploy.py script fails without it installed.

**Comment by freetimecoder** [comment]
Thank you!

Added requirement but also made it optional with this commit:
Fixed build script with commit: FreetimeStudio/Adventure-Kit@2bea57afa613b63ca8b1fe16c44965dd57fa20c7
