### ISSUE TITLE
AI custom gravity

### ISSUE THREAD

**Issue by HeroicVillain** [FreetimeStudio/Adventure-Kit-Public#6]
Can AI also use the custom gravity and walk on planetoids? Also I noticed jumping was pretty weak in the demo with planetoids, is that intended or can you not jump?

**Comment by freetimecoder** [comment]
AI can not use the custom gravity. While a character is able to, Unreal's AI Framework does not understand walking in other gravity.

Jumping is as strong as you set it but is dampened by the gravity strength of a planetoid as well.
