### ISSUE TITLE
Zone Exits (Top) do not work correctly

### ISSUE THREAD

**Issue by ghost** [FreetimeStudio/Adventure-Kit-Public#7]
There is an issue with Zone transitions, specipically top exits, it might be me doing things wrong or it might be a bug. 
I work with AdventureKit 2.0 in Unreal 4.17.2

-BP_LedgeZone_Static and all other ledge Zones do not generate any Zone Transition on top, the player cannot climb out of the Zone onto a Platform. 
-It works fine if I copy the LedgeZone_Static instaces in the example map.
-The BP_WallZone always generates those Zone Transitionson on top, and the player will climb out even through a solid wall.

I have attached two screenshots to further explain the issue.

![adventurekit zone transitition issue 2](https://user-images.githubusercontent.com/28950315/31599609-60ef36d0-b253-11e7-993b-06f5ec42150f.png)
![adventurekit zone transitition issue](https://user-images.githubusercontent.com/28950315/31599611-610a1298-b253-11e7-8bce-706274960b49.png)

**Comment by freetimecoder** [comment]
Each zone has an array of transition builders that govern which transitions are created. You can enable / disable them in the Builders list in the details panel of a zone.
