### ISSUE TITLE
Problems installing 4.17 and 4.18

### ISSUE THREAD

**Issue by Rivanna** [FreetimeStudio/Adventure-Kit-Public#8]
I have problems to install 4.17 and 4.18 from marketplace, I can install 4.17 plugin and downloaded the following zip:
https://github.com/FreetimeStudio/Adventure-Kit/tree/4.17

As it is said in the setup guide (https://github.com/FreetimeStudio/Adventure-Kit-Public/wiki/Setup)

> #Latest (UE 4.13 v2.0 Alpha 4 and later)
> 
> If you installed the plugin from the marketplace, go to UE_Install_Dir/4.XX/Engine/Plugins/Marketplace/AdvKitPlugin. If you downloaded the kit from Sellfy, extract the AdvKitPlugin folder to UE_Install_Dir/4.XX/Engine/Plugins/Marketplace/ and open it.
> Installing additional content:
> 
> You can either use the install script:
> 
> Windows: Double click the install.bat and wait for it to finish.
> Mac OS: Open a terminal, navigate to the folder and execute the following commands:
> chmod install.sh u+x
> ./install.sh
> 
> Or manually copy the folders:
> 
> Copy the content of the AdditionalContent/Templates folder to UE_Install_Dir/4.XX/Templates/
> Copy the content of the AdditionalContent/FeaturePacks folder to UE_Install_Dir/4.XX/FeaturePacks/
> 
> After restarting the editor you can now create projects with the new game templates
> You can also copy the example project in AdditionalContent/ExampleProject to your desktop or another folder and open it. The project contains all example content and game templates in one.

The main issue is that the inner directory structure doesn't have a folder of FeaturePacks in AdditionalContent folder. The only content of Additional content folder are Templates folder and ExampleProject.

I don't know how to install it, I would appreciate your help, and thanks for your time.

What steps should I to follow in order to perform the complete install?

Also install.bat is missing.

**Comment by AlexsandraSilva** [comment]
I have the same problem.

**Comment by snackzilla** [comment]
I additionally have the same problem. No install.bat, and no FeaurePacks. Freshly downloaded from the Marketplace. Is there a repo for 4.17-4.18 on this git? I don't mind installing manually, but I'd need the files.

**Comment by sirtoggle** [comment]
I have the install.bat but no FeaturePacks. so I can make the independent projects but not add features to existing projects.

**Comment by freetimecoder** [comment]
If you download from GitHub make sure to go to the releases section and download the AdvKitRelease_4XX_20X.zip, not source. The source needs to be compiled first.

Featurepacks have been fixed in 4.19 and onward. If you still want to use an older version's feature packs you can copy the folder AdditionalContent/ExampleProject/Content/AdventureKit/AK_Core to your project's Content folder into Content/AdventureKit/AK_Core. You can also open the example project and migrate the content via the content browser.
