### ISSUE TITLE
Problem with sent file

### ISSUE THREAD

**Issue by AlChaiir** [FreetimeStudio/Adventure-Kit-Public#9]
The file I`ve got after I`ve bought the pack on Sellfy was corrupted or something. I still have the file with version 4.20 but every time I "install" it on a new project the code of the whole project get`s corrupted.
I want a fixed version, please. Contact me here: defaltflogs@gmail.com

**Comment by freetimecoder** [comment]
Mail sent

**Comment by AlChaiir** [comment]
I've got nothing

Pascal Krabbe <notifications@github.com> schrieb am Di., 14. Aug. 2018
11:15:

**Comment by freetimecoder** [comment]
Maybe it went into spam? Might as well post it here then:

> Hello,
> 
> If you send me your Sellfy receipt and GitHub username to githubaccess@freetimestudio.net I can invite you into the GitHub repository where you'll be able to download the latest releases.
> 
> Kind Regards,
> Pascal Krabbe

**Comment by AlChaiir** [comment]
Receipt?
I simply received an E-Mail where the downloadable file was included.
But there's no content file and no installiert.bat included.
Later I can send you a screenshot of the file.
PS: I deleted the E-Mail because I thought it's only one file. My GitHub
username is "AlChaiir"

Pascal Krabbe <notifications@github.com> schrieb am Di., 14. Aug. 2018
13:29:

**Comment by AlChaiir** [comment]
Umm... Hello?
I still want my files

David Müller <teambluetask@gmail.com> schrieb am Di., 14. Aug. 2018 13:33:

**Comment by freetimecoder** [comment]
Can you sent me a screenshot of the file contents? Also are you sure that you have the 4.20 version? What do you mean by corrupted, does Unreal provide any error messages?

**Comment by AlChaiir** [comment]
Sure thing. Here are two screenshots. If you want a specific folder just
tell me.

2018-08-14 15:11 GMT+02:00 Pascal Krabbe <notifications@github.com>:

**Comment by freetimecoder** [comment]
Can you send it directly to githubaccess@freetimestudio.net? The email replies you have been sending have been automatically appended to the issue thread but it doesn't show the images. 

As for my other questions: Are you sure that you have the 4.20 version? What do you mean by corrupted, does Unreal provide any error messages?
